### Recuperar todo
GET http://localhost:3000/celdas

### Recuperar un dato por numeroCelda
GET http://localhost:3000/celdas/numeroCelda


### Crear un dato con POST
POST http://localhost:3000/celdas
Content-Type: application/json

{
  "placa": "MOO332",
  "estado": false,
  "numeroCelda": 3
}

### Borrar un dato
DELETE http://localhost:3000/celdas/2

### Actualizar un dato
PATCH http://localhost:3000/celdas/2
Content-Type: application/json

{
  "estado": false
}